version: "3"

services: 
    web:
        container_name: arteofyou_container
        restart: always
        build: .
        ports: ["8080:3001"]
        links: [mongo]
        volumes:
            - .:/ARTEOFYOU2
    mongo:
        container_name: mymongodatabase
        image: mongo
        ports: ["27018:27017"]
        logging: 
            driver: none
